name: Generate Changelog

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types: [created, published]

jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go environment
        uses: actions/setup-go@v2
        with:
          go-version: '1.18'

      - name: Install git-chglog
        run: |
          curl -sSL https://github.com/git-chglog/git-chglog/releases/download/v0.10.0/git-chglog_0.10.0_linux_x86_64.tar.gz | tar -xz
          sudo mv git-chglog /usr/local/bin/

      - name: Generate Changelog
        run: |
          git-chglog --next-tag v$(git describe --tags --abbrev=0) --output CHANGELOG.md

      - name: Commit and push the changelog
        run: |
          git config --global user.email "emamidadmehr@example.com"
          git config --global user.name "Dadmehr"
          git add CHANGELOG.md
          git commit -m "Update Changelog"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

